#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
JSON Data Viewer

Purpose:
View data in JSON files generated by 2_project_svtr_bidirectional.py
Display top-100 probability distributions of OCR, LM, and GT

Usage:
    python view_json_data.py <json_file> [sample_idx] [position]
    
Examples:
    # View all positions of sample #0
    python view_json_data.py output_train_long/svtr_train_long_bidirectional.json 0
    
    # View position #3 of sample #5
    python view_json_data.py output_train_long/svtr_train_long_bidirectional.json 5 3
    
    # Interactive mode (no additional parameters)
    python view_json_data.py output_train_long/svtr_train_long_bidirectional.json
"""

import json
import sys
import numpy as np


def load_json_file(json_file):
    """Load JSON file"""
    print(f"Loading file: {json_file}")
    try:
        with open(json_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        print(f"✅ Successfully loaded, total {len(data)} samples\n")
        return data
    except FileNotFoundError:
        print(f"❌ File not found: {json_file}")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"❌ JSON format error: {e}")
        sys.exit(1)


def show_sample_overview(data, sample_idx):
    """Display overview of a single sample"""
    if sample_idx >= len(data):
        print(f"❌ Sample index out of range! Maximum index: {len(data) - 1}")
        return None
    
    sample = data[sample_idx]
    
    print("="*80)
    print(f"📋 Sample #{sample_idx} Overview")
    print("="*80)
    
    # Check data structure
    if 'ocr_c100' not in sample or 'lm_c100' not in sample or 'gt_c100' not in sample:
        print("❌ Sample data incomplete, missing required fields!")
        return None
    
    ocr_c100 = sample['ocr_c100']
    lm_c100 = sample['lm_c100']
    gt_c100 = sample['gt_c100']
    
    seq_len = len(ocr_c100)
    
    print(f"Sequence Length: {seq_len}")
    print(f"OCR Data: {len(ocr_c100)} positions")
    print(f"LM  Data: {len(lm_c100)} positions")
    print(f"GT  Data: {len(gt_c100)} positions")
    
    # Check length consistency
    if len(ocr_c100) == len(lm_c100) == len(gt_c100):
        print("✅ All lengths are consistent")
    else:
        print("❌ Length mismatch!")
    
    print("\n" + "-"*80)
    print("📊 Probability Sum Statistics (All Positions)")
    print("-"*80)
    
    # Calculate probability sums
    ocr_sums = [sum(probs) for probs in ocr_c100]
    lm_sums = [sum(probs) for probs in lm_c100]
    gt_sums = [sum(probs) for probs in gt_c100]
    
    print(f"\n【OCR Probability Sum】")
    print(f"  - Mean: {np.mean(ocr_sums):.4f}")
    print(f"  - Std: {np.std(ocr_sums):.4f}")
    print(f"  - Min: {np.min(ocr_sums):.4f}")
    print(f"  - Max: {np.max(ocr_sums):.4f}")
    
    print(f"\n【LM Probability Sum】")
    print(f"  - Mean: {np.mean(lm_sums):.4f}")
    print(f"  - Std: {np.std(lm_sums):.4f}")
    print(f"  - Min: {np.min(lm_sums):.4f}")
    print(f"  - Max: {np.max(lm_sums):.4f}")
    
    print(f"\n【GT Probability Sum】")
    print(f"  - Mean: {np.mean(gt_sums):.4f}")
    print(f"  - Std: {np.std(gt_sums):.4f}")
    print(f"  - Min: {np.min(gt_sums):.4f}")
    print(f"  - Max: {np.max(gt_sums):.4f}")
    
    # Data quality check
    print("\n" + "-"*80)
    print("🔍 Data Quality Check")
    print("-"*80)
    
    if np.mean(ocr_sums) < 0.98:
        print("✅ OCR probability sum < 0.98, confidence information retained")
    else:
        print("⚠️ OCR probability sum is close to 1.0, may have been incorrectly normalized!")
    
    if np.mean(lm_sums) < 0.98:
        print("✅ LM probability sum < 0.98, confidence information retained")
    else:
        print("⚠️ LM probability sum is close to 1.0, may have been incorrectly normalized!")
    
    if abs(np.mean(gt_sums) - 1.0) < 0.01:
        print("✅ GT probability sum ≈ 1.0, as expected")
    else:
        print("⚠️ GT probability sum is not 1.0, potential issue")
    
    print("="*80)
    
    return sample


def show_position_detail(sample, position, ocr_chars=None):
    """Display detailed information of a single position"""
    ocr_c100 = sample['ocr_c100']
    lm_c100 = sample['lm_c100']
    gt_c100 = sample['gt_c100']
    
    if position >= len(ocr_c100):
        print(f"❌ Position index out of range! Maximum position: {len(ocr_c100) - 1}")
        return
    
    print("\n" + "="*80)
    print(f"🔍 Position #{position} Detailed Information")
    print("="*80)
    
    ocr_probs = ocr_c100[position]
    lm_probs = lm_c100[position]
    gt_probs = gt_c100[position]
    
    # Check lengths
    print(f"\nTop-100 Candidate Count:")
    print(f"  - OCR: {len(ocr_probs)}")
    print(f"  - LM:  {len(lm_probs)}")
    print(f"  - GT:  {len(gt_probs)}")
    
    # Probability sums
    ocr_sum = sum(ocr_probs)
    lm_sum = sum(lm_probs)
    gt_sum = sum(gt_probs)
    
    print(f"\nProbability Sum:")
    print(f"  - OCR: {ocr_sum:.6f}")
    print(f"  - LM:  {lm_sum:.6f}")
    print(f"  - GT:  {gt_sum:.6f}")
    
    # Top-10 probabilities
    print("\n" + "-"*80)
    print("📊 Top-10 Probability Distribution (Descending Order)")
    print("-"*80)
    
    # OCR Top-10
    ocr_top10_idx = np.argsort(ocr_probs)[::-1][:10]
    print(f"\n【OCR Top-10】")
    for rank, idx in enumerate(ocr_top10_idx, 1):
        print(f"  {rank:2d}. Candidate #{idx:3d}: {ocr_probs[idx]:.6f}")
    
    # LM Top-10
    lm_top10_idx = np.argsort(lm_probs)[::-1][:10]
    print(f"\n【LM Top-10】")
    for rank, idx in enumerate(lm_top10_idx, 1):
        print(f"  {rank:2d}. Candidate #{idx:3d}: {lm_probs[idx]:.6f}")
    
    # GT (find candidate with probability 1)
    gt_idx = [i for i, p in enumerate(gt_probs) if p > 0.99]
    print(f"\n【GT (Ground Truth)】")
    if gt_idx:
        for idx in gt_idx:
            print(f"  Candidate #{idx:3d}: {gt_probs[idx]:.6f} ✅")
    else:
        print("  No ground truth found (no candidate with probability = 1)")
    
    # Comparison: OCR vs LM
    print("\n" + "-"*80)
    print("🔄 OCR vs LM Comparison (Top-5)")
    print("-"*80)
    print(f"{'Rank':>4} | {'Cand':>4} | {'OCR Prob':>10} | {'LM Prob':>10} | {'Difference':>10}")
    print("-"*80)
    
    for rank in range(min(5, len(ocr_probs))):
        ocr_idx = ocr_top10_idx[rank]
        ocr_p = ocr_probs[ocr_idx]
        lm_p = lm_probs[ocr_idx]
        diff = ocr_p - lm_p
        
        print(f"{rank+1:4d} | #{ocr_idx:3d} | {ocr_p:10.6f} | {lm_p:10.6f} | {diff:+10.6f}")
    
    print("="*80)


def interactive_mode(data):
    """Interactive viewing mode"""
    print("\n" + "="*80)
    print("🔍 Interactive Viewing Mode")
    print("="*80)
    print("\nCommands:")
    print("  s <sample_idx>           - View overview of the specified sample")
    print("  p <sample_idx> <pos>     - View details of the specified position in the specified sample")
    print("  stats                    - View overall statistics")
    print("  q                        - Exit")
    print("="*80)
    
    current_sample_idx = None
    current_sample = None
    
    while True:
        cmd = input("\n>>> ").strip().split()
        
        if not cmd:
            continue
        
        if cmd[0] == 'q':
            print("Exiting interactive mode")
            break
        
        elif cmd[0] == 's':
            if len(cmd) < 2:
                print("❌ Usage: s <sample_idx>")
                continue
            
            try:
                sample_idx = int(cmd[1])
                current_sample = show_sample_overview(data, sample_idx)
                if current_sample:
                    current_sample_idx = sample_idx
            except ValueError:
                print("❌ Sample index must be an integer")
        
        elif cmd[0] == 'p':
            if len(cmd) < 3:
                print("❌ Usage: p <sample_idx> <position>")
                continue
            
            try:
                sample_idx = int(cmd[1])
                position = int(cmd[2])
                
                # Load sample if switched
                if current_sample_idx != sample_idx:
                    current_sample = show_sample_overview(data, sample_idx)
                    current_sample_idx = sample_idx
                
                if current_sample:
                    show_position_detail(current_sample, position)
            except ValueError:
                print("❌ Indices must be integers")
        
        elif cmd[0] == 'stats':
            show_overall_stats(data)
        
        else:
            print(f"❌ Unknown command: {cmd[0]}")


def show_overall_stats(data, num_samples=100):
    """Display overall statistics"""
    print("\n" + "="*80)
    print(f"📊 Overall Statistics (First {min(num_samples, len(data))} Samples)")
    print("="*80)
    
    all_ocr_sums = []
    all_lm_sums = []
    all_gt_sums = []
    all_lengths = []
    
    for i in range(min(num_samples, len(data))):
        sample = data[i]
        ocr_c100 = sample['ocr_c100']
        lm_c100 = sample['lm_c100']
        gt_c100 = sample['gt_c100']
        
        all_lengths.append(len(ocr_c100))
        
        for j in range(len(ocr_c100)):
            all_ocr_sums.append(sum(ocr_c100[j]))
            all_lm_sums.append(sum(lm_c100[j]))
            all_gt_sums.append(sum(gt_c100[j]))
    
    print(f"\n【Sequence Length】")
    print(f"  - Number of Samples: {len(all_lengths)}")
    print(f"  - Average Length: {np.mean(all_lengths):.2f}")
    print(f"  - Shortest: {np.min(all_lengths)}")
    print(f"  - Longest: {np.max(all_lengths)}")
    
    print(f"\n【OCR Probability Sum】")
    print(f"  - Mean: {np.mean(all_ocr_sums):.4f}")
    print(f"  - Std: {np.std(all_ocr_sums):.4f}")
    print(f"  - Min: {np.min(all_ocr_sums):.4f}")
    print(f"  - Max: {np.max(all_ocr_sums):.4f}")
    
    print(f"\n【LM Probability Sum】")
    print(f"  - Mean: {np.mean(all_lm_sums):.4f}")
    print(f"  - Std: {np.std(all_lm_sums):.4f}")
    print(f"  - Min: {np.min(all_lm_sums):.4f}")
    print(f"  - Max: {np.max(all_lm_sums):.4f}")
    
    print(f"\n【GT Probability Sum】")
    print(f"  - Mean: {np.mean(all_gt_sums):.4f}")
    print(f"  - Std: {np.std(all_gt_sums):.4f}")
    
    print("\n" + "-"*80)
    print("🔍 Data Quality Check")
    print("-"*80)
    
    if np.mean(all_ocr_sums) < 0.98:
        print("✅ OCR probability sum is normal, confidence information retained")
    else:
        print("⚠️ OCR probability sum is close to 1.0, may have been incorrectly normalized!")
    
    if np.mean(all_lm_sums) < 0.98:
        print("✅ LM probability sum is normal, confidence information retained")
    else:
        print("⚠️ LM probability sum is close to 1.0, may have been incorrectly normalized!")
    
    if abs(np.mean(all_gt_sums) - 1.0) < 0.01:
        print("✅ GT probability sum is normal")
    else:
        print("⚠️ GT probability sum is abnormal")
    
    print("="*80)


def main():
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python view_json_data.py <json_file> [sample_idx] [position]")
        print("\nExamples:")
        print("  # Interactive mode")
        print("  python view_json_data.py output_train_long/svtr_train_long_bidirectional.json")
        print("\n  # View sample #0")
        print("  python view_json_data.py output_train_long/svtr_train_long_bidirectional.json 0")
        print("\n  # View position #3 of sample #5")
        print("  python view_json_data.py output_train_long/svtr_train_long_bidirectional.json 5 3")
        sys.exit(1)
    
    json_file = sys.argv[1]
    
    # Load data
    data = load_json_file(json_file)
    
    if len(data) == 0:
        print("❌ Data is empty!")
        sys.exit(1)
    
    # Determine mode based on parameters
    if len(sys.argv) == 2:
        # Interactive mode
        interactive_mode(data)
    
    elif len(sys.argv) == 3:
        # View specified sample
        sample_idx = int(sys.argv[2])
        sample = show_sample_overview(data, sample_idx)
        
        if sample:
            print(f"\n💡 Tip: Use the following command to view specific positions:")
            print(f"   python view_json_data.py {json_file} {sample_idx} <position>")
    
    elif len(sys.argv) == 4:
        # View specified position of specified sample
        sample_idx = int(sys.argv[2])
        position = int(sys.argv[3])
        
        sample = show_sample_overview(data, sample_idx)
        if sample:
            show_position_detail(sample, position)
    
    else:
        print("❌ Too many parameters!")
        sys.exit(1)


if __name__ == "__main__":
    main()